version: "3.9"

services:
    je-bitsy:
        container_name: bitsy-app
        image: bitsy
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./editor:/app/editor
